### ISSUE TITLE
add-ons menu 

### ISSUE THREAD

**Issue by xdonyang** [jazz-community/rtc-workitem-bulk-mover-ui#13]
I tried with v6.0.3 and see the com.siemens.bt.jazz.services.WorkItemBulkMover.IWorkItemBulkMoverService active but there is no menu called Add-ons, did I miss anything when deploying?

From:
Download the Client Extension from the Releases page.
Download the Menu Provider from the Releases page.
Download the Web Service from the Bulk Mover Service Releases page.

The first two links point to the same files:
com.siemens.bt.jazz.ui.WorkItemBulkMover.menuProvider_1.2.2.zip
the 3rd one goes to
com.siemens.bt.jazz.services.WorkItemBulkMover.updatesite-1.2.1.zip
I downloaded both of them and followed the Installation guide to add both them.

**Comment by innerjoin** [comment]
You need to download both plugins:
- com.siemens.bt.jazz.ui.WorkItemBulkMover.menuProvider_1.2.2.zip
- com.siemens.bt.jazz.ui.WorkItemBulkMover_1.2.2.zip
One is the User Interface itself and the other is the Add-On Menu

**Comment by xdonyang** [comment]
Thanks for the info.
I am able to see Add-ons menu and did a move now in a simple test.
